version: "3.9"
services:
  prometheus:
    restart: always
    image: prom/prometheus
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-admin-api"
      - "--storage.tsdb.retention.time=14d"
    expose:
      - 9090
    ports:
      - "9090:9090"
    links:
      - mqttgateway:mqttgateway
      - node-exporter:node-exporter
      - unpoller:unpoller
    depends_on:
      - mqttgateway
      - node-exporter
      - unpoller

  node-exporter:
    restart: always
    image: prom/node-exporter:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'

  grafana:
    restart: always
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=collabnix
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - grafana:/var/lib/grafana 
    links:
      - prometheus:prometheus
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  mqttgateway:
    restart: always
    image: mqttgateway/mqttgateway
    command: '--mqtt.broker-address="tcp://host.docker.internal:1883"'
    expose:
      - 9337
    ports:
      - "9337:9337"
    extra_hosts:
      - "host.docker.internal:host-gateway" 

  unpoller:
    image: golift/unifi-poller:latest
    restart: unless-stopped
    ports:
      - '9130:9130'
    container_name: unpoller
    environment:
      - UP_INFLUXDB_DISABLE=true
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DYNAMIC=false
      - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
      - UP_PROMETHEUS_NAMESPACE=unifipoller
      - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=true
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=true
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES=true
      - UP_UNIFI_CONTROLLER_0_URL=${UNIFI_URL}
      - UP_UNIFI_CONTROLLER_0_USER=${UNIFI_USER}
      - UP_UNIFI_CONTROLLER_0_PASS=${UNIFI_PASS}

volumes:
  grafana:
  prometheus:
