version: "3.9"
services:
  prometheus:
    image: ajeetraina/prometheus-armv7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
    expose:
      - 9090
    ports:
      - "9090:9090"
    links:
      - mqttgateway:mqttgateway
      - node-exporter:node-exporter
    depends_on:
      - mqttgateway
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=collabnix
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - grafana:/var/lib/grafana 
    links:
      - prometheus:prometheus
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  mqttgateway:
    image: mqttgateway/mqttgateway
    command: '--mqtt.broker-address="tcp://host.docker.internal:1883"'
    expose:
      - 9337
    ports:
      - "9337:9337"
    extra_hosts:
      - "host.docker.internal:host-gateway" 

volumes:
  grafana:
  prometheus:
